#!/usr/bin/env python3
"""Regenerate METRICS.md from what Prometheus actually holds.

A hand-written metric list rots the moment someone ships a counter. This asks the
datasource instead, so the inventory can be regenerated rather than maintained.

    GCX_CONFIG=~/.config/gcx/soma-config.yaml python3 grafana/gen_metrics_inventory.py \
        > grafana/METRICS.md

Series counts are point-in-time cardinality, useful for spotting a label that is
about to become expensive. A family listed with 0 live series exists in the index
but is not currently reporting — that is unknown, not zero.
"""

from __future__ import annotations

import json
import subprocess
import sys
from collections import defaultdict

DATASOURCE = "grafanacloud-prom"

# Ordered: the first matching rule wins, so put the specific prefixes first.
ORIGINS: list[tuple[str, tuple[str, ...], str]] = [
    (
        "SOMA application",
        ("soma_",),
        "Emitted by SOMA's own code through `app/metrics.py`. These are the only "
        "metrics the team fully controls; every label here was chosen deliberately "
        "and must stay bounded.",
    ),
    (
        "Derived from SOMA traces",
        ("traces_spanmetrics", "traces_service_graph", "traces_target_info"),
        "Generated by Alloy connectors from the spans SOMA exports, not by SOMA. "
        "Dimensions are limited to what the connector promotes — `span_name`, "
        "`status_code`, `service_name` — so richer span attributes such as "
        "`result` or `job.id` are reachable only in Tempo.",
    ),
    (
        "SOMA HTTP auto-instrumentation",
        ("http_server", "http_client"),
        "Produced by the OpenTelemetry FastAPI and httpx instrumentation. Inbound "
        "`http_server_*` is per-route; outbound `http_client_*` carries no peer "
        "hostname, so attribute outbound calls via traces or the service graph.",
    ),
    (
        "Collector and Alloy health",
        ("otelcol_", "alloy_"),
        "The telemetry pipeline reporting on itself. Everything else on every "
        "dashboard is only as trustworthy as these.",
    ),
    (
        "Supabase integration",
        (
            "pg_",
            "physical_replication",
            "replication_",
            "pgbouncer",
            "supavisor",
            "postgrest",
            "realtime",
            "storage",
            "auth_",
            "gotrue",
            "db_",
            "deprecated_flags",
            "client_connections",
            "max_",
        ),
        "Scraped by the Grafana Cloud Supabase integration, not by SOMA. Covers "
        "Postgres internals, poolers and replication.",
    ),
    (
        "Host and runtime exporters",
        ("node_", "go_", "process_"),
        "node_exporter and Go runtime series. Note that some `node_*` series in "
        "this stack come from a macOS host (mountpoints under "
        "`/System/Volumes/...`), so they do not describe Supabase's disk.",
    ),
    (
        "Grafana Cloud meta",
        ("grafanacloud", "scrape_", "up"),
        "Billing, scrape health and target liveness supplied by Grafana Cloud.",
    ),
]

OTHER = "Unclassified"


def gcx(args: list[str]) -> dict | list:
    result = subprocess.run(
        ["gcx", *args, "-o", "json"], capture_output=True, text=True, check=False
    )
    lines = [
        line
        for line in result.stdout.splitlines()
        if '"class":"hint"' not in line and '"class": "hint"' not in line
    ]
    blob = "\n".join(lines).strip()
    if not blob:
        raise SystemExit(f"gcx {' '.join(args)} returned no JSON:\n{result.stderr}")
    return json.loads(blob)


def metric_names() -> list[str]:
    data = gcx(["metrics", "labels", "-d", DATASOURCE, "--label", "__name__"])
    values = data if isinstance(data, list) else data.get("data", data.get("values", []))
    return sorted(name for name in values if isinstance(name, str))


def series_counts() -> dict[str, int]:
    data = gcx(["metrics", "query", 'count by (__name__) ({__name__!=""})', "-d", DATASOURCE])
    result = data.get("data", {}).get("result", []) if isinstance(data, dict) else []
    return {row["metric"]["__name__"]: int(float(row["value"][1])) for row in result}


def origin_of(name: str) -> str:
    for label, prefixes, _ in ORIGINS:
        if name.startswith(prefixes):
            return label
    return OTHER


def family_of(name: str) -> str:
    for suffix in ("_bucket", "_count", "_sum", "_total"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return name


def main() -> int:
    names = metric_names()
    counts = series_counts()

    grouped: dict[str, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for name in names:
        grouped[origin_of(name)][family_of(name)].append(name)

    blurbs = {label: blurb for label, _, blurb in ORIGINS}
    blurbs[OTHER] = "Not matched by any known prefix. Worth classifying or removing."
    order = [label for label, _, _ in ORIGINS] + [OTHER]

    print("# SOMA metric inventory")
    print()
    print(
        f"{len(names)} metric names across {sum(len(f) for f in grouped.values())} families, "
        f"read from the `{DATASOURCE}` datasource."
    )
    print()
    print("Regenerate with `python3 grafana/gen_metrics_inventory.py > grafana/METRICS.md`.")
    print("Do not hand-edit below this line — it is generated.")
    print()
    print("## Summary")
    print()
    print("| Origin | Families | Metric names |")
    print("|---|---|---|")
    for label in order:
        if label in grouped:
            families = grouped[label]
            total = sum(len(v) for v in families.values())
            print(f"| {label} | {len(families)} | {total} |")
    print()

    for label in order:
        if label not in grouped:
            continue
        print(f"## {label}")
        print()
        print(blurbs[label])
        print()
        print("| Family | Series | Names |")
        print("|---|---|---|")
        for family in sorted(grouped[label]):
            members = sorted(grouped[label][family])
            live = sum(counts.get(name, 0) for name in members)
            live_text = str(live) if live else "**0 — not reporting**"
            shown = ", ".join(f"`{name}`" for name in members)
            print(f"| `{family}` | {live_text} | {shown} |")
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
